CC = gcc



all : main1_1 main1_2 main1_3 main1_4

main1_1 : main1_1.c
	$(CC) -o main1_1 main1_1.c

main1_2 : main1_2.c
	$(CC) -o main1_2 main1_2.c

main1_3 : main1_3.c
	$(CC) -o main1_3 main1_3.c

main1_4 : main1_4.c
	$(CC) -o main1_4 main1_4.c
	
.PHONY : all clean

clean :
	rm -f main1_1 main1_2 main1_3 main1_4
